<a href="https://colab.research.google.com/github/pela-andrea/Case-CoC/blob/main/Limpeza_dos_dados_para_Modelo_Preditivo_Andrea_Pel%C3%A1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Construa um modelo para prever a Participação na Carteira do Clash of Clans para cada cliente. Por favor, detalhe a abordagem de modelagem, as técnicas de ajuste e validação, e os resultados. Que insights sobre os principais impulsionadores da Participação na Carteira podemos obter das estatísticas do modelo?

#Instalação e configuração das Bibliotecas

##Declaração das LIBS

In [ ]:
!pip install category_encoders

Collecting category_encoders
  Downloading category_encoders-2.6.1-py2.py3-none-any.whl (81 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.9/81.9 kB 5.1 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.22.4)
Requirement already satisfied: scikit-learn>=0.20.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.2.2)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.10.1)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (0.13.5)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.5.3)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (0.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.5->category_encoders) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.5->category_encoders) (2022.7.1)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from patsy>=0.5.1->category_encoders) (1.16.0)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20.0->category_encoders) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20.0->category_encoders) (3.1.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.10/dist-packages (from statsmodels>=0.9.0->category_encoders) (23.1)
Installing collected packages: category_encoders
Successfully installed category_encoders-2.6.1

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
from datetime import datetime
import matplotlib.pyplot as plt
import category_encoders as ce
from sklearn.preprocessing import OneHotEncoder
%matplotlib inline
import missingno as msno
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

##Configuração do pandas

In [ ]:
pd.set_option('display.max_columns', 100)

##Importação e Extração dos dados

In [ ]:
#Carregando o dataset
df = pd.read_excel(r'/content/df_Tratado.xlsx')

# Neste projeto, as fases abaixo serão implementadas

1. Entender o problema de negócios
2. Análise exploratória
3. Pré Processamento dos dados
4. Construir o modelo preditivo
5. Avaliar o melhor modelo preditivo
6. Teste

# 1. Problema de Negócio

## Como funciona o Share of Wallet?
####O grande propósito do funcionamento do SOW é conseguir fazer o seu consumidor diminuir os valores aplicados em outras organizações, ampliando a participação do seu negócio como local desses gastos.
####Isso é feito por meio de um planejamento estratégico, que conta com um estudo bem detalhado a respeito das marcas concorrentes do seu nicho.

#2. Análise descritiva

In [ ]:
#Análise descritiva dos dados
df.describe()

,Wave,Customer ID,Super Boost,First purchase Amount,Value Tier,Number of Games,Clash of Clans Rank,Royale Clans Rank,Battle of Zombies Rank,Plants vs Zombies Rank,Clash Royale Rank,Lords Mobile Rank,Clash of Lords 2 Rank,Brave Conquest Rank,Clash of Clans SOCW,Royale Clans SOCW,Battle of Zombies SOCW,Plants vs Zombies SOCW,Clash Royale SOCW,Lords Mobile SOCW,Brave Conquest\nSOCW,Clash of Lords 2 SOCW,Other SOCW,Royale Clans User,Battle of Zombies User,Plants vs Zombies User,Clash Royale User,Lords Mobile User,Clash of Lords 2 User,Castle Clash User,Clash of Clans Rating,Royale Clans Rating,Battle of Zombies Rating,Plants vs Zombies Rating,Clash Royale Rating,Lords Mobile Rating,Clash of Lords 2 Rating,Castle Clash,Other Rating
count,11261.00,11261.00,9509.00,11261.00,11261.00,11261.00,11261.00,11261.00,11261.00,11261.00,11261.00,11261.00,11261.00,11261.00,11261.00,11261.00,11261.00,11261.00,11261.00,11261.00,11261.00,11261.00,11261.00,7214.00,7214.00,7214.00,7214.00,7214.00,7214.00,3506.00,9238.00,2219.00,955.00,2362.00,1203.00,2090.00,2268.00,480.00,766.00
mean,6.02,2430697.61,0.62,55.74,4.27,2.47,1.53,0.78,0.34,0.47,0.43,0.58,0.62,0.36,65.10,4.17,1.69,6.37,2.08,4.72,1.30,4.53,9.20,0.31,0.13,0.33,0.17,0.29,0.31,0.14,7.84,5.88,5.88,7.84,6.30,6.65,6.77,4.07,5.74
std,3.17,1249799.22,0.49,134.11,1.89,2.02,1.06,1.66,1.29,1.12,1.42,1.47,1.45,1.10,32.73,10.26,7.27,14.26,7.47,11.96,5.68,11.31,17.12,0.46,0.34,0.47,0.37,0.45,0.46,0.34,2.35,2.54,2.63,2.24,2.44,2.41,2.41,3.97,3.01
min,1.00,1000048.00,0.00,0.00,-1.00,1.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,3.00,1396093.00,0.00,12.00,2.00,1.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,33.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,7.00,5.00,5.00,7.00,5.00,5.00,6.00,0.00,4.00
50%,6.00,2055171.00,1.00,25.00,5.00,2.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,67.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,8.00,6.00,6.00,8.00,7.00,7.00,7.00,5.00,6.00
75%,9.00,3198875.00,1.00,57.00,6.00,3.00,1.50,1.00,0.00,0.00,0.00,0.00,0.00,0.00,100.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,13.00,1.00,0.00,1.00,0.00,1.00,1.00,0.00,10.00,8.00,8.00,9.00,8.00,8.00,8.00,8.00,8.00
max,11.00,6275501.00,1.00,5000.00,8.00,14.00,12.00,13.00,12.00,10.50,13.00,13.50,13.00,12.50,100.00,67.00,67.00,67.00,67.00,67.00,67.00,67.00,100.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,10.00,10.00,10.00,10.00,10.00,10.00,10.00,10.00,10.00

In [ ]:
#Formato do DataSet
df.shape

(11261, 62)

In [ ]:
#Identificação das primeiras linhas
df.head()

,Wave,Survey Date,Customer ID,First Bet date,Super Boost,Gender,Registration Platform,Platform Group,City Address,First purchase Amount,Last Purchase Date,CCY Code,Platform_Pref,Value Tier,Non-Solus?,Number of Games,Clash of Clans Rank,Royale Clans Rank,Battle of Zombies Rank,Plants vs Zombies Rank,Clash Royale Rank,Lords Mobile Rank,Clash of Lords 2 Rank,Brave Conquest Rank,Other Rank,Clash of Clans SOCW,Royale Clans SOCW,Battle of Zombies SOCW,Plants vs Zombies SOCW,Clash Royale SOCW,Lords Mobile SOCW,Brave Conquest\nSOCW,Clash of Lords 2 SOCW,Castle Clash SOW,Other SOCW,Royale Clans User,Battle of Zombies User,Plants vs Zombies User,Clash Royale User,Lords Mobile User,Clash of Lords 2 User,Castle Clash User,Other User,Clash of Clans Rating,Royale Clans Rating,Battle of Zombies Rating,Plants vs Zombies Rating,Clash Royale Rating,Lords Mobile Rating,Clash of Lords 2 Rating,Castle Clash,Other Rating,Always fun to play,Constantly launch new features/ challenges,Good Usability,Robust Mobile App,Range of game modes/ features,Multi-player gaming,Rewards Loyalty,Doesn't drain my phone's battery,Easy in-app purchase,Customer Service
0,1,2011-11-01,1000323,2011-01-22 12:46:43,1.0,NaN,Mobile: iPhone,iOS,Dromore,5.9270,2014-06-20 01:58:19,GBP,Multi,6,Yes,2,1.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.666667,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.333333,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,3,4,5,5,NaN,5,NaN,5,5
1,1,2011-11-01,1000599,2007-11-21 08:13:59,0.0,M,Internet,Desktop,kildare,50.0000,2014-01-03 13:30:50,EUR,Internet Only,5,No,1,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,2011-11-01,1004867,2011-04-09 15:37:53,1.0,NaN,Internet,Desktop,Dundee,11.4168,2014-06-22 22:50:01,GBP,Internet Only,7,No,1,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,2011-11-01,1015458,2007-01-05 17:06:52,NaN,NaN,Internet,Desktop,London,37.2467,2013-11-23 16:47:48,GBP,Internet_75%_+,5,Yes,4,1.0,2.0,0.0,0.0,0.0,0.0,0.0,3.0,4.0,0.400000,0.3,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.300000,1.0,0.0,0.0,0.0,0.0,0.0,NaN,1,10.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,5,5,5,4,4,NaN,5,NaN,5,5
4,1,2011-11-01,1017048,2009-09-12 12:13:05,1.0,NaN,Internet,Desktop,Slough,11.4456,2014-06-19 17:38:38,GBP,Internet_75%_+,6,No,1,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11261 entries, 0 to 11260
Data columns (total 62 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Wave                                       11261 non-null  int64
 1   Survey Date                                11261 non-null  datetime64[ns]
 2   Customer ID                                11261 non-null  int64
 3   First Bet date                             11261 non-null  datetime64[ns]
 4   Super Boost                                9509 non-null   float64
 5   Gender                                     722 non-null    object
 6   Registration Platform                      11261 non-null  object
 7   Platform Group                             11261 non-null  object
 8   City Address                               11261 non-null  object
 9   First purchase Amount                      11261 non-null  int64
 10  Last Purchase Date                         11261 non-null  datetime64[ns]
 11  CCY Code                                   11261 non-null  object
 12  Platform Pref                              11239 non-null  object
 13  Value Tier                                 11261 non-null  int64
 14  Non-Solus?                                 11261 non-null  bool
 15  Number of Games                            11261 non-null  int64
 16  Clash of Clans Rank                        11261 non-null  float64
 17  Royale Clans Rank                          11261 non-null  float64
 18  Battle of Zombies Rank                     11261 non-null  float64
 19  Plants vs Zombies Rank                     11261 non-null  float64
 20  Clash Royale Rank                          11261 non-null  float64
 21  Lords Mobile Rank                          11261 non-null  float64
 22  Clash of Lords 2 Rank                      11261 non-null  float64
 23  Brave Conquest Rank                        11261 non-null  float64
 24  Clash of Clans SOCW                        11261 non-null  int64
 25  Royale Clans SOCW                          11261 non-null  int64
 26  Battle of Zombies SOCW                     11261 non-null  int64
 27  Plants vs Zombies SOCW                     11261 non-null  int64
 28  Clash Royale SOCW                          11261 non-null  int64
 29  Lords Mobile SOCW                          11261 non-null  int64
 30  Brave Conquest
SOCW                        11261 non-null  int64
 31  Clash of Lords 2 SOCW                      11261 non-null  int64
 32  Other SOCW                                 11261 non-null  int64
 33  Royale Clans User                          7214 non-null   float64
 34  Battle of Zombies User                     7214 non-null   float64
 35  Plants vs Zombies User                     7214 non-null   float64
 36  Clash Royale User                          7214 non-null   float64
 37  Lords Mobile User                          7214 non-null   float64
 38  Clash of Lords 2 User                      7214 non-null   float64
 39  Castle Clash User                          3506 non-null   float64
 40  Other User                                 7848 non-null   object
 41  Clash of Clans Rating                      9238 non-null   float64
 42  Royale Clans Rating                        2219 non-null   float64
 43  Battle of Zombies Rating                   955 non-null    float64
 44  Plants vs Zombies Rating                   2362 non-null   float64
 45  Clash Royale Rating                        1203 non-null   float64
 46  Lords Mobile Rating                        2090 non-null   float64
 47  Clash of Lords 2 Rating                    2268 non-null   float64
 48  Castle Clash                               480 non-null    float64
 49  Other  Rating                              766 non-null    float64
 50  Always fun to play                         9313 non-null   object
 51  Constantly launch new features challenges  9401 non-null   object
 52  Good Usability                             9320 non-null   object
 53  Robust Mobile App                          9325 non-null   object
 54  Range of game modes features               9478 non-null   object
 55  Multi-player gaming                        7161 non-null   object
 56  Rewards Loyalty                            9336 non-null   object
 57  Doesn't drain my phones battery            7280 non-null   object
 58  Easy in-app purchase                       9337 non-null   object
 59  Customer Service                           9370 non-null   object
 60  SuperBoost YES                             11261 non-null  bool
 61  SuperBoost NO                              11261 non-null  bool
dtypes: bool(3), datetime64[ns](3), float64(25), int64(14), object(17)
memory usage: 5.1+ MB

In [ ]:
##Porcentagem de valores nulos em todas as variáveis
porcentagem_nulos = (df.isnull().sum() / len(df)) * 100

with pd.option_context('display.max_rows', None):
 print(porcentagem_nulos)

Wave                                          0.000000
Survey Date                                   0.000000
Customer ID                                   0.000000
First Bet date                                0.000000
Super Boost                                  15.558121
Gender                                       93.588491
Registration Platform                         0.000000
Platform Group                                0.000000
City Address                                  0.000000
First purchase Amount                         0.000000
Last Purchase Date                            0.000000
CCY Code                                      0.000000
Platform Pref                                 0.195365
Value Tier                                    0.000000
Non-Solus?                                    0.000000
Number of Games                               0.000000
Clash of Clans Rank                           0.000000
Royale Clans Rank                             0.000000
Battle of Zombies Rank                        0.000000
Plants vs Zombies Rank                        0.000000
Clash Royale Rank                             0.000000
Lords Mobile Rank                             0.000000
Clash of Lords 2 Rank                         0.000000
Brave Conquest Rank                           0.000000
Clash of Clans SOCW                           0.000000
Royale Clans SOCW                             0.000000
Battle of Zombies SOCW                        0.000000
Plants vs Zombies SOCW                        0.000000
Clash Royale SOCW                             0.000000
Lords Mobile SOCW                             0.000000
Brave Conquest\nSOCW                          0.000000
Clash of Lords 2 SOCW                         0.000000
Other SOCW                                    0.000000
Royale Clans User                            35.938194
Battle of Zombies User                       35.938194
Plants vs Zombies User                       35.938194
Clash Royale User                            35.938194
Lords Mobile User                            35.938194
Clash of Lords 2 User                        35.938194
Castle Clash User                            68.865998
Other User                                   30.308143
Clash of Clans Rating                        17.964657
Royale Clans Rating                          80.294823
Battle of Zombies Rating                     91.519403
Plants vs Zombies Rating                     79.024953
Clash Royale Rating                          89.317112
Lords Mobile Rating                          81.440369
Clash of Lords 2 Rating                      79.859693
Castle Clash                                 95.737501
Other  Rating                                93.197762
Always fun to play                           17.298641
Constantly launch new features challenges    16.517183
Good Usability                               17.236480
Robust Mobile App                            17.192079
Range of game modes features                 15.833407
Multi-player gaming                          36.408845
Rewards Loyalty                              17.094397
Doesn't drain my phones battery              35.352100
Easy in-app purchase                         17.085516
Customer Service                             16.792470
SuperBoost YES                                0.000000
SuperBoost NO                                 0.000000
dtype: float64

In [ ]:
##Verificando as colunas do df em lista
df.columns.tolist()

['Wave',
 'Survey Date',
 'Customer ID',
 'First Bet date',
 'Super Boost',
 'Gender',
 'Registration Platform',
 'Platform Group',
 'City Address',
 'First purchase Amount',
 'Last Purchase Date',
 'CCY Code',
 'Platform Pref',
 'Value Tier',
 'Non-Solus?',
 'Number of Games',
 'Clash of Clans Rank',
 'Royale Clans Rank',
 'Battle of Zombies Rank',
 'Plants vs Zombies Rank',
 'Clash Royale Rank',
 'Lords Mobile Rank',
 'Clash of Lords 2 Rank',
 'Brave Conquest Rank',
 'Clash of Clans SOCW',
 'Royale Clans SOCW',
 'Battle of Zombies SOCW',
 'Plants vs Zombies SOCW',
 'Clash Royale SOCW',
 'Lords Mobile SOCW',
 'Brave Conquest\nSOCW',
 'Clash of Lords 2 SOCW',
 'Other SOCW',
 'Royale Clans User',
 'Battle of Zombies User',
 'Plants vs Zombies User',
 'Clash Royale User',
 'Lords Mobile User',
 'Clash of Lords 2 User',
 'Castle Clash User',
 'Other User',
 'Clash of Clans Rating',
 'Royale Clans Rating',
 'Battle of Zombies Rating',
 'Plants vs Zombies Rating',
 'Clash Royale Rating',
 'Lords Mobile Rating',
 'Clash of Lords 2 Rating',
 'Castle Clash ',
 'Other  Rating',
 'Always fun to play',
 'Constantly launch new features challenges',
 'Good Usability',
 'Robust Mobile App',
 'Range of game modes features',
 'Multi-player gaming',
 'Rewards Loyalty',
 "Doesn't drain my phones battery",
 'Easy in-app purchase',
 'Customer Service',
 'SuperBoost YES',
 'SuperBoost NO']

#Pré Processamento dos dados

##Separando as variáveis que serão utilizadas no modelo preditivo

Existem métodos estatísticos que poderiam orientar melhor a escolha das variáveis dentro deste dataset, para o melhor resultado no modelo preditivio a ser criado. Como por exemplo o método **Método F-valor ANOVA para Seleção de Variáveis **, por se tratar de um problema de regressão e as variáveis serem mistas (numéricas e categóricas).

ANOVA é uma técnica estatística que realiza análise de variância e os métodos baseados no teste F estimam o grau de dependência linear entre duas variáveis aleatórias.

Entretanto, este dataset ainda possui muitas variáveis que possuem números nulos e a decisão foi não utilizar tais variáveis.

In [ ]:
df.columns.values

array(['Wave', 'Survey Date', 'Customer ID', 'First Bet date', 'Gender',
       'Registration Platform', 'Platform Group', 'City Address',
       'First purchase Amount', 'Last Purchase Date', 'CCY Code',
       'Platform Pref', 'Value Tier', 'Non-Solus?', 'Number of Games',
       'Clash of Clans Rank', 'Royale Clans Rank',
       'Battle of Zombies Rank', 'Plants vs Zombies Rank',
       'Clash Royale Rank', 'Lords Mobile Rank', 'Clash of Lords 2 Rank',
       'Brave Conquest Rank', 'Clash of Clans SOCW', 'Royale Clans SOCW',
       'Battle of Zombies SOCW', 'Plants vs Zombies SOCW',
       'Clash Royale SOCW', 'Lords Mobile SOCW', 'Brave Conquest\nSOCW',
       'Clash of Lords 2 SOCW', 'Other SOCW', 'Royale Clans User',
       'Battle of Zombies User', 'Plants vs Zombies User',
       'Clash Royale User', 'Lords Mobile User', 'Clash of Lords 2 User',
       'Castle Clash User', 'Other User', 'Clash of Clans Rating',
       'Royale Clans Rating', 'Battle of Zombies Rating',
       'Plants vs Zombies Rating', 'Clash Royale Rating',
       'Lords Mobile Rating', 'Clash of Lords 2 Rating', 'Castle Clash ',
       'Other  Rating', 'Always fun to play',
       'Constantly launch new features challenges', 'Good Usability',
       'Robust Mobile App', 'Range of game modes features',
       'Multi-player gaming', 'Rewards Loyalty',
       "Doesn't drain my phones battery", 'Easy in-app purchase',
       'Customer Service', 'SuperBoost YES', 'SuperBoost NO'],
      dtype=object)

In [ ]:
#Separando as variáveis que serão utilizadas no modelo.
df1_col =  ['Wave', 'Survey Date', 'Customer ID', 'First Bet date',
 'Platform Group', 'City Address',  'First purchase Amount',
 'Last Purchase Date', 'CCY Code', 'Value Tier',
 'Non-Solus?', 'Number of Games', 'Clash of Clans Rank',
 'Royale Clans Rank', 'Battle of Zombies Rank',
 'Plants vs Zombies Rank', 'Clash Royale Rank', 'Lords Mobile Rank',
 'Clash of Lords 2 Rank', 'Brave Conquest Rank', 'Clash of Clans SOCW',
 'Royale Clans SOCW', 'Battle of Zombies SOCW', 'Plants vs Zombies SOCW',
 'Clash Royale SOCW', 'Lords Mobile SOCW', 'Brave Conquest\nSOCW',
 'Clash of Lords 2 SOCW', 'Other SOCW', 'Always fun to play',
 'Constantly launch new features challenges', 'Good Usability',
 'Robust Mobile App', 'Range of game modes features',
 'Multi-player gaming', 'Rewards Loyalty', "Doesn't drain my phones battery",
 'Easy in-app purchase', 'Customer Service', 'SuperBoost YES', 'SuperBoost NO', 'Clash of Clans Rating']

In [ ]:
df1 = df.filter(items = df1_col)

#Engenharia de atributos

In [ ]:
df1.rename(columns={'Survey Date':'surve_ydate',
                   'Customer ID':'custumer_id',
                   'First Bet date':'first_bet_date',
                   'Platform Group':'platform_group',
                   'City Address':'city',
                   'First purchase Amount':'first_purchase',
                   'Last Purchase Date':'last_purchase_date',
                   'CCY Code': 'ccy',
                   'Value Tier':'value_tier',
                   'Non-Solus?':'non_solus',
                   'Number of Games':'number_of_games',
                   'Clash of Clans Rank':'clashofclans_rank',
                   'Royale Clans Rank':'royaleclash_rank',
                   'Battle of Zombies Rank':'battleofzombies_rank',
                   'Plants vs Zombies Rank':'plantsvszombies_rank',
                   'Clash Royale Rank':'clashroyale_rank',
                   'Lords Mobile Rank':'lordsmobile_rank',
                   'Clash of Lords 2 Rank':'clashof_lords2_rank',
                   'Brave Conquest Rank':'braveconquest_rank',
                   'Clash of Clans SOCW':'clashofclans_sow',
                   'Royale Clans SOCW':'royaleclans_sow',
                   'Battle of Zombies SOCW':'battleofzombies_sow',
                   'Plants vs Zombies SOCW':'plantsvszombies_sow',
                   'Clash Royale SOCW':'clashroyale_sow',
                   'Lords Mobile SOCW':'lorsmobile_sow',
                   'Brave Conquest\nSOCW':'braveconquest_sow',
                   'Clash of Lords 2 SOCW':'clashoflords2_sow',
                   'Other SOCW':'other_sow',
                   'Always fun to play':'always_fun_to_play',
                   'Constantly launch new features challenges':'launch_new_features',
                   'Good Usability':'good_usability',
                   'Robust Mobile App':'robust_mobile_app',
                   'Range of game modes features':'range_ofgamesmodes_feat',
                   'Multi-player gaming':'multiplayer_gaming',
                   'Rewards Loyalty':'rewards_loyalty',
                   "Doesn't drain my phones battery":'doesnt_drains_battery',
                   'Easy in-app purchase':'easy_inapp_purchase',
                   'Customer Service':'customer_service',
                   'SuperBoost YES':'sb_yes',
                   'SuperBoost NO':'sb_no',
                   'Clash of Clans Rating':'coc_rating',
},inplace=True)

In [ ]:
df1.columns.values

array(['Wave', 'surve_ydate', 'custumer_id', 'first_bet_date',
       'platform_group', 'city', 'first_purchase', 'last_purchase_date',
       'ccy', 'value_tier', 'non_solus', 'number_of_games',
       'clashofclans_rank', 'royaleclash_rank', 'battleofzombies_rank',
       'plantsvszombies_rank', 'clashroyale_rank', 'lordsmobile_rank',
       'clashof_lords2_rank', 'braveconquest_rank', 'clashofclans_sow',
       'royaleclans_sow', 'battleofzombies_sow', 'plantsvszombies_sow',
       'clashroyale_sow', 'lorsmobile_sow', 'braveconquest_sow',
       'clashoflords2_sow', 'other_sow', 'always_fun_to_play',
       'launch_new_features', 'good_usability', 'robust_mobile_app',
       'range_ofgamesmodes_feat', 'multiplayer_gaming', 'rewards_loyalty',
       'doesnt_drains_battery', 'easy_inapp_purchase', 'customer_service',
       'sb_yes', 'sb_no', 'coc_rating'], dtype=object)

In [ ]:
df1_col = ['Wave', 'surve_ydate', 'custumer_id', 'first_bet_date',
       'platform_group', 'city', 'first_purchase', 'last_purchase_date',
       'ccy', 'value_tier', 'non_solus', 'number_of_games',
       'clashofclans_rank', 'royaleclash_rank', 'battleofzombies_rank',
       'plantsvszombies_rank', 'clashroyale_rank', 'lordsmobile_rank',
       'clashof_lords2_rank', 'braveconquest_rank', 'clashofclans_sow',
       'royaleclans_sow', 'battleofzombies_sow', 'plantsvszombies_sow',
       'clashroyale_sow', 'lorsmobile_sow', 'braveconquest_sow',
       'clashoflords2_sow', 'other_sow', 'always_fun_to_play',
       'launch_new_features', 'good_usability', 'robust_mobile_app',
       'range_ofgamesmodes_feat', 'multiplayer_gaming', 'rewards_loyalty',
       'doesnt_drains_battery', 'easy_inapp_purchase', 'customer_service',
       'sb_yes', 'sb_no', 'coc_rating']

##Usando Hot Encoding para configurar as variáveis categórias em numéricas

In [ ]:
df1['platform_group'].value_counts()

Desktop    9458
iOS         859
Other       688
Android     256
Name: platform_group, dtype: int64

In [ ]:
df1['ccy'].value_counts()

GBP    8001
EUR    3260
Name: ccy, dtype: int64

##Usando Hot Encoding para configurar as variáveis categórias em numéricas

In [ ]:
columns_to_encode = ['platform_group', 'ccy']

In [ ]:
one_hot_encoder = OneHotEncoder(sparse=False)

In [ ]:
one_hot_encoder.fit(df1[columns_to_encode])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

OneHotEncoder(sparse=False, sparse_output=False)

In [ ]:
encoded_columns = one_hot_encoder.transform(df1[columns_to_encode])

In [ ]:
df_encoded = pd.DataFrame(encoded_columns, columns=one_hot_encoder.get_feature_names_out(columns_to_encode))

In [ ]:
df_encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11261 entries, 0 to 11260
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   platform_group_Android  11261 non-null  float64
 1   platform_group_Desktop  11261 non-null  float64
 2   platform_group_Other    11261 non-null  float64
 3   platform_group_iOS      11261 non-null  float64
 4   ccy_EUR                 11261 non-null  float64
 5   ccy_GBP                 11261 non-null  float64
dtypes: float64(6)
memory usage: 528.0 KB

In [ ]:
df1 = pd.concat([df1, df_encoded], axis=1)

In [ ]:
df1

,Wave,surve_ydate,custumer_id,first_bet_date,platform_group,city,first_purchase,last_purchase_date,ccy,value_tier,non_solus,number_of_games,clashofclans_rank,royaleclash_rank,battleofzombies_rank,plantsvszombies_rank,clashroyale_rank,lordsmobile_rank,clashof_lords2_rank,braveconquest_rank,clashofclans_sow,royaleclans_sow,battleofzombies_sow,plantsvszombies_sow,clashroyale_sow,lorsmobile_sow,braveconquest_sow,clashoflords2_sow,other_sow,always_fun_to_play,launch_new_features,good_usability,robust_mobile_app,range_ofgamesmodes_feat,multiplayer_gaming,rewards_loyalty,doesnt_drains_battery,easy_inapp_purchase,customer_service,sb_yes,sb_no,coc_rating,platform_group_Android,platform_group_Desktop,platform_group_Other,platform_group_iOS,ccy_EUR,ccy_GBP
0,1,2011-11-01,1000323,2011-01-22 12:46:43,iOS,dromore,5,2014-06-20 01:58:19,GBP,6,True,2,1.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,67,0,0,0,0,0,0,0,33,5.000000,3.000000,4.000000,5.000000,5.000000,3.911231,5.000000,4.081092,5.000000,5.000000,False,False,9.000000,0.0,0.0,0.0,1.0,0.0,1.0
1,1,2011-11-01,1000599,2007-11-21 08:13:59,Desktop,kildare,50,2014-01-03 13:30:50,EUR,5,False,1,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,100,0,0,0,0,0,0,0,0,3.810963,3.192537,3.555126,3.552531,3.619949,2.819917,3.561025,2.926757,3.116087,3.518014,False,False,7.836761,0.0,1.0,0.0,0.0,1.0,0.0
2,1,2011-11-01,1004867,2011-04-09 15:37:53,Desktop,dundee,11,2014-06-22 22:50:01,GBP,7,False,1,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,100,0,0,0,0,0,0,0,0,3.810963,3.192537,3.555126,3.552531,3.619949,2.819917,3.561025,2.926757,3.116087,3.518014,False,False,7.836761,0.0,1.0,0.0,0.0,0.0,1.0
3,1,2011-11-01,1015458,2007-01-05 17:06:52,Desktop,london,37,2013-11-23 16:47:48,GBP,5,True,4,1.0,2.0,0.0,0.0,0.0,0.0,0.0,3.0,40,30,0,0,0,0,0,0,30,5.000000,5.000000,5.000000,4.000000,4.000000,3.599240,5.000000,4.083221,5.000000,5.000000,False,True,10.000000,0.0,1.0,0.0,0.0,0.0,1.0
4,1,2011-11-01,1017048,2009-09-12 12:13:05,Desktop,slough,11,2014-06-19 17:38:38,GBP,6,False,1,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,100,0,0,0,0,0,0,0,0,3.810963,3.192537,3.555126,3.552531,3.619949,2.819917,3.561025,2.926757,3.116087,3.518014,False,False,7.836761,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11256,11,2014-05-01,4730733,2008-03-11 12:36:28,Desktop,greystones,50,2014-06-13 08:19:03,EUR,2,True,2,1.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,67,0,33,0,0,0,0,0,0,5.000000,3.000000,3.000000,1.000000,4.000000,0.000000,0.000000,4.000000,4.000000,4.000000,False,False,7.000000,0.0,1.0,0.0,0.0,1.0,0.0
11257,11,2014-05-01,4736498,2009-04-08 17:23:07,Desktop,mogeely,20,2014-06-26 18:54:49,EUR,3,True,2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,67,0,0,0,0,0,0,0,33,5.000000,4.000000,5.000000,5.000000,4.000000,4.000000,5.000000,0.000000,4.000000,4.000000,False,False,7.000000,0.0,1.0,0.0,0.0,1.0,0.0
11258,11,2014-05-01,4736498,2007-12-24 18:37:20,Desktop,baile atha cliath,50,2014-06-13 21:34:58,EUR,2,False,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100,0,0,0,0,0,0,0,0,0.000000,3.000000,3.000000,4.000000,4.000000,0.000000,3.000000,0.000000,0.000000,0.000000,False,False,8.000000,0.0,1.0,0.0,0.0,1.0,0.0
11259,11,2014-05-01,4740822,2011-08-25 12:21:17,Desktop,milton keynes,22,2014-06-24 16:56:39,GBP,5,True,2,1.5,0.0,0.0,1.5,0.0,0.0,0.0,0.0,50,0,0,50,0,0,0,0,0,4.000000,2.000000,4.000000,4.000000,4.000000,3.000000,4.000000,4.000000,3.000000,3.000000,False,False,8.000000,0.0,1.0,0.0,0.0,0.0,1.0
11260,11,2014-05-01,4740962,2014-01-16 13:37:15,Desktop,drogheda,50,2014-06-26 16:47:23,EUR,4,True,3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.5,50,0,0,0,0,0,0,0,50,4.000000,3.000000,4.000000,4.000000,2.000000,4.000000,3.000000,1.000000,3.000000,4.000000,False,False,6.000000,0.0,1.0,0.0,0.0,1.0,0.0

In [ ]:
df1 = df1.drop(['platform_group', 'ccy'], axis=1)

In [ ]:
#Salvando o arquivo Tratado em .xlsx
df1.to_excel('/content/sample_data/df_clean.xlsx', index=False , engine='openpyxl')

Exception ignored in: <function ZipFile.__del__ at 0x7fa2bbca7490>
Traceback (most recent call last):
  File "/usr/lib/python3.10/zipfile.py", line 1821, in __del__
    self.close()
  File "/usr/lib/python3.10/zipfile.py", line 1838, in close
    self.fp.seek(self.start_dir)
ValueError: seek of closed file

#Calculando os melhores Features para o modelo

O método SelectKBest com o score de informação mútua clássica (mutual info classic) é a ferramenta mais utilizada na seleção de características (feature selection). O Mutual Info Classic quantifica a dependência mútua entre duas variáveis. No contexto da seleção de características, ele é usado para avaliar a relação entre cada característica (variável independente) e a variável alvo (variável dependente). Ele mede o quanto de informação a presença ou ausência de uma determinada característica pode fornecer sobre a variável alvo.

In [ ]:
#Carregando o dataset
df = pd.read_excel(r'/content/df_clean.xlsx')

In [ ]:
colnames = ['Wave', 'custumer_id', 'value_tier', 'non_solus',
       'number_of_games', 'clashofclans_rank', 'royaleclash_rank',
       'battleofzombies_rank', 'plantsvszombies_rank', 'clashroyale_rank',
       'lordsmobile_rank', 'clashof_lords2_rank', 'braveconquest_rank',
       'royaleclans_sow', 'battleofzombies_sow', 'plantsvszombies_sow',
       'clashroyale_sow', 'lorsmobile_sow', 'braveconquest_sow',
       'clashoflords2_sow', 'other_sow', 'always_fun_to_play',
       'launch_new_features', 'good_usability', 'robust_mobile_app',
       'range_ofgamesmodes_feat', 'multiplayer_gaming', 'rewards_loyalty',
       'doesnt_drains_battery', 'easy_inapp_purchase', 'customer_service',
       'sb_yes', 'sb_no', 'coc_rating', 'platform_group_Android',
       'platform_group_Desktop', 'platform_group_Other', 'platform_group_iOS',
       'ccy_EUR', 'ccy_GBP', 'clashofclans_sow']

In [ ]:
df1 = df[colnames]

In [ ]:
from sklearn.feature_selection import SelectKBest, mutual_info_classif

X = df1.drop(['clashofclans_sow'], axis=1)
y = df1['clashofclans_sow']

selector = SelectKBest(score_func=mutual_info_classif, k=10)
selector.fit(X, y)
features = selector.transform(X)

#Variáveis escolhidas para a criação do modelo preditivo da Share of Wallet, do jogo Clash of Clans

'non_solus', 'number_of_games', 'clashofclans_rank', 'royaleclash_rank',
       'clashof_lords2_rank', 'royaleclans_sow', 'plantsvszombies_sow',
       'lorsmobile_sow', 'clashoflords2_sow', 'other_sow'

In [ ]:
selected_features_names = X.columns[selector.get_support()]
print(selected_features_names)

Index(['non_solus', 'number_of_games', 'clashofclans_rank', 'royaleclash_rank',
       'clashof_lords2_rank', 'royaleclans_sow', 'plantsvszombies_sow',
       'lorsmobile_sow', 'clashoflords2_sow', 'other_sow'],
      dtype='object')

In [ ]:
df_selecionado = df1[['non_solus', 'number_of_games', 'clashofclans_rank', 'royaleclash_rank',
       'clashof_lords2_rank', 'royaleclans_sow', 'plantsvszombies_sow',
       'lorsmobile_sow', 'clashoflords2_sow', 'other_sow', 'clashofclans_sow']]

In [ ]:
df_selecionado

,non_solus,number_of_games,clashofclans_rank,royaleclash_rank,clashof_lords2_rank,royaleclans_sow,plantsvszombies_sow,lorsmobile_sow,clashoflords2_sow,other_sow
0,True,2,1.0,1.0,0.0,0,0,0,0,33
1,False,1,1.0,1.0,0.0,0,0,0,0,0
2,False,1,1.0,1.0,0.0,0,0,0,0,0
3,True,4,1.0,2.0,0.0,30,0,0,0,30
4,False,1,1.0,1.0,0.0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
11256,True,2,1.0,0.0,0.0,0,0,0,0,0
11257,True,2,1.0,0.0,0.0,0,0,0,0,33
11258,False,1,1.0,0.0,0.0,0,0,0,0,0
11259,True,2,1.5,0.0,0.0,0,50,0,0,0
11260,True,3,1.0,0.0,0.0,0,0,0,0,50

In [ ]:
#Salvando o arquivo Tratado em .xlsx
df_selecionado.to_excel('/content/sample_data/df_selecionado.xlsx', index=False , engine='openpyxl')

#Criando o modelo RandomForest de Regressão

utilizar dados aleatorios pra verificar a previsao deste metodo e como testar a acuracia

In [ ]:
##Treino e previsao, separando uma parte dos dados orginais pra fazer a previsao e apos testar a acuracia

# Definir as variáveis de entrada (X) e a variável de saída (y)
X = df[['non_solus', 'number_of_games', 'clashofclans_rank', 'royaleclash_rank',
       'clashof_lords2_rank', 'royaleclans_sow', 'plantsvszombies_sow',
       'lorsmobile_sow', 'clashoflords2_sow', 'other_sow']]  #variáveis escolhidas
y = df['clashofclans_sow']  #coluna alvo

# Dividir o conjunto de dados em treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

# Criar o modelo de Random Forest
model = RandomForestRegressor()

# Treinar o modelo com os dados de treinamento
model.fit(X_train, y_train)

# Fazer previsões usando o modelo treinado nos dados de teste
y_pred = model.predict(X_test)

# Calcular a acurácia do modelo usando a métrica R²
r2 = r2_score(y_test, y_pred)

# Imprimir a acurácia do modelo
print('Acurácia:', r2)

Acurácia: 0.9999342571765754

#Validação

####Coeficiente de Determinação (R²): Mede a proporção da variância da variável de saída que é explicada pelo modelo. Ele varia entre 0 e 1, onde 1 indica um ajuste perfeito do modelo aos dados. Quanto maior o valor de R², melhor é o ajuste do modelo.
####Erro Médio Absoluto (MAE): Média das diferenças absolutas entre as previsões do modelo e os valores reais da variável de saída. Ele fornece uma medida da média do erro absoluto cometido pelo modelo. Quanto menor o valor do MAE, melhor é o ajuste do modelo.
####Erro Quadrático Médio (MSE): Média dos erros ao quadrado entre as previsões do modelo e os valores reais da variável de saída. Ele fornece uma medida do erro médio quadrático cometido pelo modelo. Quanto menor o valor do MSE, melhor é o ajuste do modelo.
####Raiz do Erro Quadrático Médio (RMSE):A raiz quadrada do MSE e fornece uma medida do erro médio quadrático em escala original.

In [ ]:

# Calcular o R²
r2 = r2_score(y_test, y_pred)

# Calcular o MAE
mae = mean_absolute_error(y_test, y_pred)

# Calcular o MSE
mse = mean_squared_error(y_test, y_pred)

# Calcular o RMSE
rmse = mean_squared_error(y_test, y_pred, squared=False)

# Imprimir as métricas
print('R²:', r2)
print('MAE:', mae)
print('MSE:', mse)
print('RMSE:', rmse)

R²: 0.9999342571765754
MAE: 0.019809143364403016
MSE: 0.07060164225477143
RMSE: 0.2657096954474402

Modelo Criado e validado.

#Referências Bibliográficas

##Singh, Kiran. Design and Development of a Mobile Game using Unity. Bachelor's thesis, Tampere University of Applied Sciences, Tampere, Finland, 2021.

##Vuckovac, D. (2018). Towards Monitoring and Building Customer Share of Wallet in Physical Retail with In-Store and Mobile Information Systems. Research Collection ETH Zurich. (Identificador permanente: 20.500.11850/303419)

##Li, X., Shemshadi, A., Olech, L. P., & Michalewicz, Z. (Ano não fornecido). Customer Wallet Share Estimation for Manufacturers based on Transaction Data. Escola de Ciência da Computação, Universidade de Adelaide, Adelaide, SA 5005, Austrália. Disponível em: [https://cs.adelaide.edu.au/~zbyszek/Papers/AusDM_2019.pdf]

##Bruce, A., & Bruce, P. (2019). Estatística prática para cientistas de dados: 50 conceitos essenciais. Edição Português. Alta Books.